Небольшая работа над интерефейсом пользователя
OpenGeekBrains/Enigma pull request #12
Opened 2020-07-28 22:31 UTC by kanadeiar

2020-07-29 10:58 UTC, WolfManR requested changes

2020-07-29 10:58 UTC, WolfManR commented on src/Enigma/Clients/WPF/Enigma.Client.WPF/Views/Windows/MainWindow.xaml
> +        Width="800" Height="450" MinWidth="600" MinHeight="300" WindowStartupLocation="CenterScreen">
указание MinWidth на данный момент не требуется, так как в будущем шаблон интерфейса будет изменятся от размера окна

2020-07-29 10:59 UTC, WolfManR commented
создай прототип окна авторизации

2020-07-29 11:49 UTC, kanadeiar commented
Задача в работе: 

- [ ] #13 Разработка прототипа окна авторизации

2020-07-29 18:29 UTC, kanadeiar commented
Готого!

2020-07-29 19:06 UTC, WolfManR requested changes

2020-07-29 19:06 UTC, WolfManR commented on src/Enigma/Clients/WPF/Enigma.Client.WPF/Views/Windows/AuthWindow.xaml
> +    </Grid>
Исправь, сейчас это Z - образный интерфейс, заголовки должны быть над полем ввода.
Так же между полями ввода должно быть расстояние больше чем между заголовком и полем ввода.
И оставь место сверху или сбоку на возможный логотип, тут на своё усмотрение, можно будет его даже за поля ввода кинуть

2020-07-29 19:06 UTC, WolfManR commented on src/Enigma/Clients/WPF/Enigma.Client.WPF/Views/Windows/AuthWindow.xaml
> +        <TextBlock Text="Вход в систему Энигма" HorizontalAlignment="Center" VerticalAlignment="Bottom" Grid.ColumnSpan="2" FontSize="32"/>
такая подробность излишня, это можно оставить на логику формы редактирования, а какой программе принадлежит укажут лого и цветовая схема окна

2020-07-30 12:30 UTC, MrAliev commented
Надо бы завести отдельный ресурс под все текстовые свойства визуальных компонентов, и в разметке использовать не хардкодный текст, а ссылку не элемент ресурса.

2020-07-30 17:35 UTC, kanadeiar commented on src/Enigma/Clients/WPF/Enigma.Client.WPF/Views/Windows/AuthWindow.xaml
> +        <TextBlock Text="Вход в систему Энигма" HorizontalAlignment="Center" VerticalAlignment="Bottom" Grid.ColumnSpan="2" FontSize="32"/>
Текстовый блок удалю

2020-07-30 17:36 UTC, kanadeiar commented on src/Enigma/Clients/WPF/Enigma.Client.WPF/Views/Windows/AuthWindow.xaml
> +    </Grid>
Поменяю их местами

2020-07-30 17:55 UTC, MrAliev commented
> **Основное окно**

- [ ] Разбить окно на отдельные UserControl

- [ ] Поработать над масштабируемостью окна (минимальные размеры и т.д.) Интерфейс не должен быть кривым при любых размерах окна. Возможно - подумать над разной компоновкой в минимальном и развернутом состоянии.

- [ ] Вынести все статические строковые данные в отдельный ресурс.

- [ ] Кнопка "отмена" - она нужна?

- [ ] Кнопка "Смайлики" - реализовать логику через триггер. По нажатию справа должен появляться контролл с этим под этот контент, а при повторном нажатии - контролл должен коллапсировать.

- [ ] Добавить многострочность в поле ввода сообщения. При чем стоит подумать над возможностью автоматического увеличения поля ввода (до каких-то разумных пределов), после достижения которого - активировать вертикальный скроллинг.

остальное подумаем по мере развития

2020-07-30 17:57 UTC, MrAliev submitted a review, later dismissed
https://github.com/OpenGeekBrains/Enigma/pull/12#issuecomment-666564093

2020-07-30 17:57 UTC, MrAliev commented on src/Enigma/Clients/WPF/Enigma.Client.WPF/Views/Windows/MainWindow.xaml
> +                <Button Content="Отправить!" DockPanel.Dock="Left"/>
```suggestion
                <Button Content="Отправить!" DockPanel.Dock="Left"/> Все статические текстовые данные вынести в ресурс, для поддержки интерфейсом разных языков в будущем
```

2020-07-30 17:57 UTC, MrAliev commented on src/Enigma/Clients/WPF/Enigma.Client.WPF/Views/Windows/AuthWindow.xaml
> +    </Grid>
```suggestion
    </Grid>
    Добавить поле ввода адреса сервера для подключения
```

2020-07-30 18:00 UTC, WolfManR commented on src/Enigma/Clients/WPF/Enigma.Client.WPF/Views/Windows/AuthWindow.xaml
> +    </Grid>
```suggestion
    <StackPanel Margin="10">
        <TextBlock Text="Логин:" HorizontalAlignment="Right" Margin="5,0,0,2"/>
        <TextBox x:Name="StringTextBoxLogin" Width="100" HorizontalAlignment="Left"/>
        
        <TextBlock Text="Пароль:" HorizontalAlignment="Right" Margin="5,15,0,2"/>
        <PasswordBox x:Name="StringPasswordBoxPassword" Width="100" HorizontalAlignment="Left"/>
        
        <Button Content="Вход в Энигму" Margin="0,15,0,0"  FontSize="16"/>
    </StackPanel>
```

пример ухода от Z-образного интерфейса.

2020-07-30 18:46 UTC, MrAliev submitted a review, later dismissed
[Задачи по доработке](https://github.com/OpenGeekBrains/Enigma/projects/1#card-42104873)

2020-07-30 21:15 UTC, WolfManR approved these changes

2020-07-30 21:16 UTC, WolfManR commented
позже улучшишь дизайн

2020-07-30 21:16 UTC, merged